#!/bin/zsh
# ghostty-zmx E2E harness library.
#
# Provides reusable functions for disposable Ghostty-tip E2E scenarios:
#   - fixture lifecycle (sshd Docker container up/down)
#   - disposable state (GHOSTTY_ZMX_DATA_HOME / STATE_HOME tmpdirs)
#   - Ghostty-tip launch with a disposable config (no user-session disruption)
#   - AppleScript input injection + assertions
#   - remote-state assertions (zmx list, remote-layout read)
#
# Sourced by individual e2e/*.zsh scenario scripts. Never sourced by unit tests
# (tests/) — this library drives a live Ghostty process and Docker containers.
#
# Usage in a scenario:
#   source "${0:A:h}/lib/harness.zsh"
#   gzmx_e2e_init
#   gzmx_e2e_fixture_sshd_up
#   gzmx_e2e_ghostty_launch
#   gzmx_e2e_type "ssh gzmx-fixture"
#   gzmx_e2e_assert_remote_clients 1
#   gzmx_e2e_cleanup

emulate -L zsh
setopt local_options no_sh_word_split err_return

# --- configuration -----------------------------------------------------------

GZMX_E2E_GHOSTTY_APP=${GHOSTTY_APP_NAME:-Ghostty-tip}
GZMX_E2E_GHOSTTY_BIN="/Applications/${GZMX_E2E_GHOSTTY_APP}.app/Contents/MacOS/${GZMX_E2E_GHOSTTY_APP}"
GZMX_E2E_REPO_DIR="${0:A:h:h:h}"
GZMX_E2E_FIXTURE_DIR="$GZMX_E2E_REPO_DIR/e2e/fixtures/sshd"
GZMX_E2E_MOCK_TSH_DIR="$GZMX_E2E_REPO_DIR/e2e/fixtures/tsh-mock"
GZMX_E2E_SSH_PORT=${GZMX_E2E_SSH_PORT:-2222}
GZMX_E2E_FIXTURE_HOST="gzmx-fixture"
GZMX_E2E_TMPDIR=""
GZMX_E2E_DATA_HOME=""
GZMX_E2E_STATE_HOME=""
GZMX_E2E_GHOSTTY_PID=""
GZMX_E2E_USE_MOCK_TSH="0"

# Enable the mock-tsh fixture: subsequent gzmx_e2e_ghostty_launch will prepend
# the mock tsh to PATH so the widget exercises the tsh code path against the
# sshd fixture (no real Teleport cluster needed).
gzmx_e2e_use_mock_tsh() {
  GZMX_E2E_USE_MOCK_TSH="1"
  [[ -n "$GZMX_E2E_SSHCONFIG" ]] || gzmx_e2e_fail "call gzmx_e2e_fixture_sshd_up before gzmx_e2e_use_mock_tsh"
  # Write a PATH-prepend snippet into the data home so the managed shell sees
  # the mock tsh. Ghostty's --env=PATH is clobbered by macOS path_helper
  # (runs in /etc/zprofile -> .zprofile), so we prepend via a file the
  # session-manager-early.zsh sources. The snippet exports PATH so the widget
  # (which runs in the surface shell's zle context) finds the mock tsh.
  mkdir -p "$GZMX_E2E_DATA_HOME/bin"
  ln -sf "$GZMX_E2E_MOCK_TSH_DIR/tsh" "$GZMX_E2E_DATA_HOME/bin/tsh" 2>/dev/null || true
  cat > "$GZMX_E2E_DATA_HOME/e2e-path.zsh" <<EOF
# Auto-generated by ghostty-zmx E2E harness: prepend mock-tsh to PATH so the
# widget finds the mock tsh (real PATH was clobbered by macOS path_helper).
export PATH="$GZMX_E2E_DATA_HOME/bin:\$PATH"
EOF
}
GZMX_E2E_SSHCONFIG=""
GZMX_E2E_STARTED_DOCKER=0
GZMX_E2E_STARTED_GHOSTTY=0

# --- logging -----------------------------------------------------------------

gzmx_e2e_log() { print -P -- "%F{blue}e2e%f $*" >&2 }
gzmx_e2e_pass() { print -P -- "%F{green}✓ PASS%f $*" >&2 }
gzmx_e2e_fail() {
  print -P -- "%F{red}✗ FAIL%f $*" >&2
  # Preserve the tmpdir on failure for post-mortem inspection.
  GZMX_E2E_KEEP_TMPDIR=1
  # Print debug log tail before cleanup.
  gzmx_e2e_debug_tail 50
  gzmx_e2e_cleanup
  exit 1
}
gzmx_e2e_warn() { print -P -- "%F{yellow}! warn%f $*" >&2 }

# --- lifecycle ---------------------------------------------------------------

gzmx_e2e_init() {
  emulate -L zsh
  GZMX_E2E_TMPDIR="$(mktemp -d /tmp/gzmx-e2e-XXXXXX)"
  GZMX_E2E_DATA_HOME="$GZMX_E2E_TMPDIR/data"
  GZMX_E2E_STATE_HOME="$GZMX_E2E_TMPDIR/state"
  mkdir -p "$GZMX_E2E_DATA_HOME" "$GZMX_E2E_STATE_HOME"
  GZMX_E2E_SSHCONFIG="$GZMX_E2E_TMPDIR/sshconfig"
  gzmx_e2e_log "tmpdir=$GZMX_E2E_TMPDIR"
}

# Bring up the sshd Docker fixture if not already running. Writes an sshconfig
# that maps GZMX_E2E_FIXTURE_HOST to localhost:GZMX_E2E_SSH_PORT using the
# fixture's generated key. Idempotent: if a container with our name is already
# up, reuses it.
gzmx_e2e_fixture_sshd_up() {
  emulate -L zsh
  # Already running?
  if docker ps --format '{{.Names}}' 2>/dev/null | grep -qx ghostty-zmx-sshd-fixture; then
    gzmx_e2e_log "sshd fixture already running"
  else
    gzmx_e2e_log "starting sshd fixture"
    ( cd "$GZMX_E2E_FIXTURE_DIR" && ./up.sh ) || gzmx_e2e_fail "sshd fixture up failed"
    GZMX_E2E_STARTED_DOCKER=1
  fi
  # up.sh generates the fixture key at /tmp/ghostty-zmx-docker-fixture/id_ed25519
  # (shared across runs). Use that canonical location so the harness and the
  # fixture's own sshconfig agree.
  local key="/tmp/ghostty-zmx-docker-fixture/id_ed25519"
  [[ -r "$key" ]] || gzmx_e2e_fail "fixture ssh key missing: $key (run up.sh first)"
  cat > "$GZMX_E2E_SSHCONFIG" <<EOF
Host $GZMX_E2E_FIXTURE_HOST
  HostName 127.0.0.1
  Port $GZMX_E2E_SSH_PORT
  User gzmx
  IdentityFile $key
  StrictHostKeyChecking no
  UserKnownHostsFile /dev/null
  LogLevel ERROR
EOF
  # Smoke-test the fixture.
  ssh -F "$GZMX_E2E_SSHCONFIG" "$GZMX_E2E_FIXTURE_HOST" 'echo fixture-ok' >/dev/null 2>&1 \
    || gzmx_e2e_fail "cannot reach sshd fixture"
  gzmx_e2e_log "sshd fixture reachable"
}

gzmx_e2e_fixture_sshd_down() {
  emulate -L zsh
  [[ "$GZMX_E2E_STARTED_DOCKER" == "1" ]] || return 0
  gzmx_e2e_log "stopping sshd fixture"
  ( cd "$GZMX_E2E_FIXTURE_DIR" && ./down.sh ) 2>/dev/null || true
}

# Install ghostty-zmx server-side files on the sshd fixture via the tar-over-ssh
# bootstrap (mirrors `ghostty-zmx install-server` but standalone).
gzmx_e2e_fixture_install_server() {
  emulate -L zsh
  local install_dir="$HOME/.config/ghostty-zmx"
  [[ -d "$install_dir" ]] || gzmx_e2e_fail "laptop install missing; run ghostty-zmx install first"
  local tmpdir="/tmp/ghostty-zmx-server-install.e2e.$$"
  local -a remote_cmd=(
    "set -e"
    "tmpdir='$tmpdir'"
    "rm -rf \"\$tmpdir\""
    "mkdir -p \"\$tmpdir\""
    "cd \"\$tmpdir\""
    "tar xzf -"
    "./install-server.sh --yes"
    "rc=$?"
    "cd /"
    "rm -rf \"\$tmpdir\""
    "exit \$rc"
  )
  COPYFILE_DISABLE=1 tar --no-mac-metadata --format ustar -czf - \
    -C "$install_dir" \
    install-server.sh session-manager.zsh session-manager-lib.zsh \
    ghostty-zmx-remote-layout terminfo/xterm-ghostty.terminfo 2>/dev/null \
    | ssh -F "$GZMX_E2E_SSHCONFIG" "$GZMX_E2E_FIXTURE_HOST" "${(j:;:)remote_cmd}" \
    || gzmx_e2e_fail "server install on fixture failed"
  gzmx_e2e_log "server files installed on fixture"
}

# Reset the fixture's ghostty-zmx server-side state so prior runs don't leak
# `present` rows into the next scenario. Wipes remote-layout, remote-layout.rev,
# the lock dir, and kills any lingering zmx sessions. Must be called after
# install_server (so the helper is present) and before any scenario logic.
gzmx_e2e_fixture_reset_server_state() {
  emulate -L zsh
  local zmx_bin
  zmx_bin="$(gzmx_e2e_fixture_zmx)"
  ssh -F "$GZMX_E2E_SSHCONFIG" "$GZMX_E2E_FIXTURE_HOST" "
    rm -rf ~/.local/share/ghostty-zmx/remote-layout ~/.local/share/ghostty-zmx/remote-layout.rev ~/.local/share/ghostty-zmx/remote-layout.lock
    # Kill any lingering zmx sessions (gzr-* and zmx-*). zmx list prints
    # 'name=<session>' as the first whitespace-delimited token.
    for s in \$($zmx_bin list 2>/dev/null | sed -n 's/.*name=\(gzr-[A-Za-z0-9-]*\).*/\1/p'); do
      $zmx_bin kill \"\$s\" >/dev/null 2>&1 || true
    done
    mkdir -p ~/.local/share/ghostty-zmx
  " 2>/dev/null || true
  gzmx_e2e_log "fixture server state reset"
}

# Launch Ghostty-tip directly (NOT via `open -na`, which attaches to an
# already-running instance and breaks isolation). Launching the binary as a
# child process gives us an exact PID to track and kill, plus a clean
# AppleScript surface (one process = one app = unambiguous window counts).
# Does NOT use -e /bin/zsh (triggers the macOS execute prompt).
gzmx_e2e_ghostty_launch() {
  emulate -L zsh
  [[ -x "$GZMX_E2E_GHOSTTY_BIN" ]] || gzmx_e2e_fail "Ghostty binary not found: $GZMX_E2E_GHOSTTY_BIN"
  # Pre-seed remote-hosts so the poller knows the fixture transport. Only
  # pre-seed if the file does not already exist: a reopen (Cmd-Q preservation
  # scenario) must preserve the widget-discovered zmx path (6th field), which
  # the restore reads to build the projection command. Clobbering it on
  # relaunch would drop the absolute zmx path, causing the reopened projection
  # to use bare `zmx` (not on the non-interactive remote PATH) and fail.
  if [[ ! -f "$GZMX_E2E_DATA_HOME/remote-hosts" ]]; then
    if [[ "$GZMX_E2E_USE_MOCK_TSH" == "1" ]]; then
      printf '%s\ttsh\t0.6.0\tactive\ttsh ssh\t/home/gzmx/.local/bin/zmx\n' \
        "$GZMX_E2E_FIXTURE_HOST" > "$GZMX_E2E_DATA_HOME/remote-hosts"
    else
      printf '%s\tssh\t0.6.0\tactive\tssh -t -F %s %s\n' \
        "$GZMX_E2E_FIXTURE_HOST" "$GZMX_E2E_SSHCONFIG" "$GZMX_E2E_FIXTURE_HOST" \
        > "$GZMX_E2E_DATA_HOME/remote-hosts"
    fi
  fi
  # Launch as a child process; disown so the harness's own exit doesn't kill it
  # prematurely (we kill it explicitly in gzmx_e2e_ghostty_quit).
  # If mock-tsh is enabled, prepend it to PATH so the widget finds our `tsh`.
  local _path_env="${PATH}"
  [[ "$GZMX_E2E_USE_MOCK_TSH" == "1" ]] && _path_env="$GZMX_E2E_MOCK_TSH_DIR:${PATH}"
  "$GZMX_E2E_GHOSTTY_BIN" \
    --env=GHOSTTY_ZMX_AUTO_ATTACH=1 \
    --env=GHOSTTY_ZMX_DEBUG=1 \
    --env=GHOSTTY_ZMX_DATA_HOME="$GZMX_E2E_DATA_HOME" \
    --env=GHOSTTY_ZMX_STATE_HOME="$GZMX_E2E_STATE_HOME" \
    --env=PATH="$_path_env" \
    --env=GHOSTTY_ZMX_E2E_SSH_CONFIG="$GZMX_E2E_SSHCONFIG" \
    --env=GHOSTTY_ZMX_E2E_FIXTURE_USER=gzmx \
    --env=GHOSTTY_ZMX_E2E_FIXTURE_HOST="$GZMX_E2E_FIXTURE_HOST" \
    --window-save-state=never \
    --confirm-close-surface=false \
    --osc-color-report-format=none \
    >/dev/null 2>&1 &
  GZMX_E2E_GHOSTTY_PID=$!
  GZMX_E2E_STARTED_GHOSTTY=1
  disown "$GZMX_E2E_GHOSTTY_PID" 2>/dev/null || true
  # Wait for Ghostty to be AppleScript-addressable and report a surface.
  local i
  for (( i=1; i<=40; i++ )); do
    kill -0 "$GZMX_E2E_GHOSTTY_PID" 2>/dev/null || gzmx_e2e_fail "Ghostty exited during launch"
    if osascript -e "tell application \"$GZMX_E2E_GHOSTTY_APP\" to get version" >/dev/null 2>&1; then
      break
    fi
    sleep 0.5
  done
  # Wait for at least one window + a focused terminal.
  for (( i=1; i<=40; i++ )); do
    local wc="$(osascript -e "tell application \"$GZMX_E2E_GHOSTTY_APP\" to count of windows" 2>/dev/null)"
    [[ "$wc" == <-> && "$wc" -ge 1 ]] && break
    sleep 0.5
  done
  gzmx_e2e_log "Ghostty launched pid=$GZMX_E2E_GHOSTTY_PID"
}

# Quit the disposable Ghostty we launched (do NOT touch a user's real session).
# Kills the whole process group so the reaper/poller children die too.
gzmx_e2e_ghostty_quit() {
  emulate -L zsh
  setopt local_options no_err_return
  [[ "$GZMX_E2E_STARTED_GHOSTTY" == "1" ]] || return 0
  [[ -n "$GZMX_E2E_GHOSTTY_PID" ]] || return 0
  # Kill the main Ghostty process; this also tears down its surfaces, which
  # causes the manager's reaper/poller children to exit on their next cycle.
  kill "$GZMX_E2E_GHOSTTY_PID" 2>/dev/null || true
  local i
  for (( i=1; i<=20; i++ )); do
    kill -0 "$GZMX_E2E_GHOSTTY_PID" 2>/dev/null || break
    sleep 0.25
  done
  kill -9 "$GZMX_E2E_GHOSTTY_PID" 2>/dev/null || true
  # Sweep any orphaned reaper/poller children the manager spawned under the
  # disposable runtime dir. These are identified by the runtime path pattern,
  # which is unique to this harness run (GZMX_E2E_GHOSTTY_PID).
  pkill -9 -f "ghostty-zmx-501/(reaper|remote-poller)-${GZMX_E2E_GHOSTTY_PID}" 2>/dev/null || true
  GZMX_E2E_STARTED_GHOSTTY=0
}

# --- input injection ---------------------------------------------------------

# Type text into the focused terminal of the front window and press Enter.
gzmx_e2e_type() {
  emulate -L zsh
  setopt local_options no_err_return
  local text="$1"
  osascript <<OSA 2>/dev/null || true
tell application "$GZMX_E2E_GHOSTTY_APP"
  set w to front window
  set tb to selected tab of w
  set tm to focused terminal of tb
  input text "$text" to tm
  send key "enter" to tm
end tell
OSA
}

# Bring window N (1-indexed) to the front and make it active.
gzmx_e2e_activate_window() {
  emulate -L zsh
  setopt local_options no_err_return
  local idx="$1"
  osascript <<OSA 2>/dev/null || true
tell application "$GZMX_E2E_GHOSTTY_APP"
  set w to item $idx of windows
  activate window w
  set index of w to 1
end tell
OSA
}

# Create a native split in the front window's focused terminal via AppleScript.
# This creates a real split surface with the default shell (no `command` set),
# so the new surface's shell sources .zprofile/.zshrc and the inherit hook runs
# — exactly the native-split-then-inherit code path under test. More reliable
# than simulating Cmd+D via System Events (which needs Accessibility +
# frontmost + timing).
gzmx_e2e_split_focused() {
  emulate -L zsh
  setopt local_options no_err_return
  local direction="${1:-right}"
  osascript <<OSA 2>/dev/null || true
tell application "$GZMX_E2E_GHOSTTY_APP"
  set w to front window
  set tb to selected tab of w
  set tm to focused terminal of tb
  set cfg to new surface configuration
  set t to split tm direction $direction with configuration cfg
end tell
OSA
}

# Type text into window N (1-indexed), focused terminal of its selected tab.
# Activates the window first so input lands in the right pane.
gzmx_e2e_type_in_window() {
  emulate -L zsh
  setopt local_options no_err_return
  local idx="$1" text="$2"
  osascript <<OSA 2>/dev/null || true
tell application "$GZMX_E2E_GHOSTTY_APP"
  set w to item $idx of windows
  activate window w
  set tb to selected tab of w
  set tm to focused terminal of tb
  input text "$text" to tm
  send key "enter" to tm
end tell
OSA
}

# Type text WITHOUT pressing Enter (for pre-fill scenarios).
gzmx_e2e_type_no_enter() {
  emulate -L zsh
  local text="$1"
  osascript <<OSA 2>/dev/null
tell application "$GZMX_E2E_GHOSTTY_APP"
  set w to front window
  set tb to selected tab of w
  set tm to focused terminal of tb
  input text "$text" to tm
end tell
OSA
}

# Send a Ghostty key (e.g. "cmd+d", "cmd+t", "cmd+shift+d") to the focused terminal.
# Send a Ghostty keybind (e.g. "cmd+d", "cmd+t", "cmd+shift+d") to the
# focused terminal. Ghostty's AppleScript `send key` sends the key to the
# terminal PTY as INPUT, not as a keybind action — so it does NOT trigger
# splits/tabs. To trigger a Ghostty keybind, we use System Events `keystroke`
# which dispatches a real key event that Ghostty's keybind handler sees.
# Requires Accessibility permission for the controlling process (osascript).
gzmx_e2e_send_key() {
  emulate -L zsh
  setopt local_options no_err_return
  local key="$1" mods="" key_char=""
  # Parse "cmd+d", "cmd+shift+d", "ctrl+t" into a key char + modifiers.
  # Modifiers: cmd, shift, ctrl, alt (-> option).
  local k="$key"
  [[ " $k " == *" cmd "* || " $k " == *" super "* ]] && mods="$mods command"
  [[ " $k " == *" shift "* ]] && mods="$mods shift"
  [[ " $k " == *" ctrl "* ]] && mods="$mods control"
  [[ " $k " == *" alt "* || " $k " == *" option "* ]] && mods="$mods option"
  # The final token after the last "+" is the key char.
  key_char="${k##*+}"
  [[ -n "$key_char" ]] || return 0
  # Ensure Ghostty is frontmost, then send the keystroke via System Events.
  osascript <<OSA 2>/dev/null || true
tell application "$GZMX_E2E_GHOSTTY_APP" to activate
tell application "System Events"
  keystroke "$key_char" {$mods}
end tell
OSA
}

# --- assertions --------------------------------------------------------------

# Assert the number of windows reported by Ghostty.
gzmx_e2e_assert_window_count() {
  emulate -L zsh
  local expected="$1" actual
  actual="$(osascript -e "tell application \"$GZMX_E2E_GHOSTTY_APP\" to count of windows" 2>/dev/null)"
  [[ "$actual" == "$expected" ]] \
    || gzmx_e2e_fail "window count: expected $expected, got $actual"
  gzmx_e2e_pass "window count == $expected"
}

# Wait up to N seconds for a condition (function name) to return 0.
gzmx_e2e_wait_for() {
  emulate -L zsh
  local seconds="$1" cond_fn="$2"
  local i
  for (( i=1; i<=seconds*4; i++ )); do
    "$cond_fn" && return 0
    sleep 0.25
  done
  return 1
}

# The absolute zmx path on the fixture (zmx is NOT on the non-interactive PATH —
# it's only added in .zshrc, mirroring pcad-dev). All fixture zmx calls must use
# this absolute path. Probed once and cached.
GZMX_E2E_FIXTURE_ZMX=""

gzmx_e2e_fixture_zmx() {
  emulate -L zsh
  [[ -n "$GZMX_E2E_FIXTURE_ZMX" ]] && { print -r -- "$GZMX_E2E_FIXTURE_ZMX"; return 0 }
  GZMX_E2E_FIXTURE_ZMX="$(ssh -F "$GZMX_E2E_SSHCONFIG" "$GZMX_E2E_FIXTURE_HOST" \
    'command -v zmx 2>/dev/null || ls /home/gzmx/.local/bin/zmx 2>/dev/null || echo zmx' 2>/dev/null)"
  print -r -- "$GZMX_E2E_FIXTURE_ZMX"
}

# Assert the fixture has N attached clients on gzr-* sessions.
gzmx_e2e_assert_remote_clients() {
  emulate -L zsh
  local expected="$1" actual zmx_bin
  zmx_bin="$(gzmx_e2e_fixture_zmx)"
  actual="$(ssh -F "$GZMX_E2E_SSHCONFIG" "$GZMX_E2E_FIXTURE_HOST" \
    "$zmx_bin list 2>/dev/null | grep 'name=gzr-' | grep -c 'clients=[1-9]'" 2>/dev/null)"
  [[ "$actual" == "$expected" ]] \
    || gzmx_e2e_fail "remote clients: expected $expected, got $actual"
  gzmx_e2e_pass "remote clients == $expected"
}

# Wait for N attached remote clients (polls, since attach is async over ssh).
gzmx_e2e_wait_remote_clients() {
  emulate -L zsh
  local expected="$1" seconds="${2:-30}" actual i zmx_bin
  zmx_bin="$(gzmx_e2e_fixture_zmx)"
  for (( i=1; i<=seconds*4; i++ )); do
    actual="$(ssh -F "$GZMX_E2E_SSHCONFIG" "$GZMX_E2E_FIXTURE_HOST" \
      "$zmx_bin list 2>/dev/null | grep 'name=gzr-' | grep -c 'clients=[1-9]'" 2>/dev/null)"
    [[ "$actual" == "$expected" ]] && { gzmx_e2e_pass "remote clients == $expected (after ${i} polls)"; return 0; }
    sleep 0.25
  done
  gzmx_e2e_fail "remote clients never reached $expected (last=$actual)"
}

# Assert a marker string is present in a remote session's zmx history (scrollback).
gzmx_e2e_assert_remote_history_contains() {
  emulate -L zsh
  local session="$1" marker="$2" hist zmx_bin
  zmx_bin="$(gzmx_e2e_fixture_zmx)"
  hist="$(ssh -F "$GZMX_E2E_SSHCONFIG" "$GZMX_E2E_FIXTURE_HOST" "$zmx_bin history $session 2>/dev/null" 2>/dev/null)"
  [[ "$hist" == *"$marker"* ]] \
    || gzmx_e2e_fail "marker '$marker' not in $session history"
  gzmx_e2e_pass "marker '$marker' found in $session history"
}

# Assert NO control-sequence leak (OSC 11 response bytes) in a remote session's
# zmx history. The leak manifests as `11;rgb:...` or `;rgb:...` in the
# scrollback. The fix is laptop-side: `osc-color-report-format = none` makes
# Ghostty not respond to OSC 4/10/11 color queries, so no response bytes are
# generated to leak. CSI 6n (cursor-position) responses are a separate,
# lower-severity known limitation (no Ghostty config disables DSR) and are not
# asserted here.
gzmx_e2e_assert_no_query_leak() {
  emulate -L zsh
  local session="$1" hist zmx_bin
  zmx_bin="$(gzmx_e2e_fixture_zmx)"
  hist="$(ssh -F "$GZMX_E2E_SSHCONFIG" "$GZMX_E2E_FIXTURE_HOST" "$zmx_bin history $session 2>/dev/null" 2>/dev/null)"
  if [[ "$hist" == *"11;rgb:"* || "$hist" == *";rgb:"* ]]; then
    print -r -- "$hist" | grep -E "11;rgb:|;rgb:" | head -3 >&2
    gzmx_e2e_fail "query-response leak detected in $session history"
  fi
  gzmx_e2e_pass "no query-response leak in $session history"
}

# Assert the remote shell's cwd for a session (via zmx run pwd).
gzmx_e2e_assert_remote_cwd() {
  emulate -L zsh
  local session="$1" expected="$2" raw zmx_bin
  zmx_bin="$(gzmx_e2e_fixture_zmx)"
  # zmx run injects the command into the session PTY; the output includes the
  # command echo, the result, and a ZMX_TASK_COMPLETED marker. The pwd result is
  # a line that is exactly the expected absolute path; match it directly.
  raw="$(ssh -F "$GZMX_E2E_SSHCONFIG" "$GZMX_E2E_FIXTURE_HOST" "$zmx_bin run $session pwd 2>/dev/null" 2>/dev/null)"
  if print -r -- "$raw" | grep -qF -- "$expected"; then
    gzmx_e2e_pass "remote cwd == $expected"
    return 0
  fi
  local hist
  hist="$(ssh -F "$GZMX_E2E_SSHCONFIG" "$GZMX_E2E_FIXTURE_HOST" "$zmx_bin history $session 2>/dev/null" 2>/dev/null)"
  print -r -- "$hist" | tail -20 >&2
  gzmx_e2e_fail "remote cwd: expected $expected, not found in raw: $raw"
}

# Return the remote-layout row (TSV) for a session, or empty if not present.
gzmx_e2e_remote_layout_row() {
  emulate -L zsh
  local session="$1" helper=/home/gzmx/.config/ghostty-zmx/ghostty-zmx-remote-layout
  ssh -F "$GZMX_E2E_SSHCONFIG" "$GZMX_E2E_FIXTURE_HOST" \
    "$helper read 2>/dev/null" 2>/dev/null | awk -F '\t' -v s="$session" '$5 == s { print }'
}

# --- debug -------------------------------------------------------------------

gzmx_e2e_debug_tail() {
  emulate -L zsh
  local n="${1:-40}"
  gzmx_e2e_log "debug.log tail:"
  tail -n "$n" "$GZMX_E2E_STATE_HOME/debug.log" 2>/dev/null >&2 || print "  (no debug.log)" >&2
}

# --- cleanup -----------------------------------------------------------------

gzmx_e2e_cleanup() {
  emulate -L zsh
  setopt local_options no_err_return
  gzmx_e2e_ghostty_quit
  gzmx_e2e_fixture_sshd_down
  if [[ "${GZMX_E2E_KEEP_TMPDIR:-0}" != "1" && -n "$GZMX_E2E_TMPDIR" ]]; then
    rm -rf "$GZMX_E2E_TMPDIR" 2>/dev/null
  else
    [[ -n "$GZMX_E2E_TMPDIR" ]] && gzmx_e2e_warn "tmpdir preserved: $GZMX_E2E_TMPDIR"
  fi
}

# Install cleanup on exit (normal or signal).
trap 'gzmx_e2e_cleanup' INT TERM HUP EXIT
